// Indonesia curated sample data.
// This adapter is an explicit fallback seed, not a scraper. Each URL points to a
// public job portal search or career page that can later be replaced by a real API.

import { JobPost, JobSourceAdapter } from '../types'

interface IndonesiaSampleJob {
  id: string
  title: string
  company: string
  location: string
  workMode: JobPost['workMode']
  type: JobPost['employmentType']
  experienceLevel: JobPost['experienceLevel']
  tags: string[]
  url: string
  sourcePortal: string
  description: string
  requiredSkills: string[]
  publishedDaysAgo: number
}

export const INDONESIA_SAMPLE_JOBS: IndonesiaSampleJob[] = [
  {
    id: 'indo-sample-1',
    title: 'Backend Developer Intern',
    company: 'PT Nusantara Digital API',
    location: 'Jakarta, Indonesia',
    workMode: 'hybrid',
    type: 'internship',
    experienceLevel: 'internship',
    tags: ['Node.js', 'Express', 'PostgreSQL', 'REST API', 'Magang'],
    url: 'https://glints.com/id/opportunities/jobs/explore?keyword=backend%20developer%20intern',
    sourcePortal: 'Glints',
    description: 'Program magang backend untuk mahasiswa atau fresh graduate. Fokus pada REST API, PostgreSQL, authentication, Git workflow, dan debugging API.',
    requiredSkills: ['JavaScript', 'Node.js', 'Express', 'PostgreSQL', 'REST API', 'Git'],
    publishedDaysAgo: 2,
  },
  {
    id: 'indo-sample-2',
    title: 'Junior Backend Engineer',
    company: 'Satu Data Teknologi',
    location: 'Bandung, Indonesia',
    workMode: 'onsite',
    type: 'full-time',
    experienceLevel: 'junior',
    tags: ['Node.js', 'PostgreSQL', 'Supabase', 'API', 'Junior'],
    url: 'https://www.kalibrr.id/job-board/te/backend-developer/jobs',
    sourcePortal: 'Kalibrr',
    description: 'Role junior untuk membangun API internal, query PostgreSQL, dan integrasi Supabase dengan bimbingan senior engineer.',
    requiredSkills: ['Node.js', 'PostgreSQL', 'Supabase', 'REST API', 'Git'],
    publishedDaysAgo: 4,
  },
  {
    id: 'indo-sample-3',
    title: 'Software Engineer Intern - Backend Platform',
    company: 'Karya Logistik Indonesia',
    location: 'Remote Indonesia',
    workMode: 'remote',
    type: 'internship',
    experienceLevel: 'internship',
    tags: ['Backend', 'TypeScript', 'Express', 'PostgreSQL', 'Remote'],
    url: 'https://www.linkedin.com/jobs/search/?keywords=software%20engineer%20intern%20backend&location=Indonesia',
    sourcePortal: 'LinkedIn Jobs',
    description: 'Internship remote untuk membantu membangun service backend, endpoint validasi, dan dokumentasi API untuk produk logistik.',
    requiredSkills: ['TypeScript', 'Node.js', 'Express', 'PostgreSQL', 'API Documentation'],
    publishedDaysAgo: 5,
  },
  {
    id: 'indo-sample-4',
    title: 'Fresh Graduate Backend Developer',
    company: 'Ruang Karya Teknologi',
    location: 'Jakarta, Indonesia',
    workMode: 'hybrid',
    type: 'full-time',
    experienceLevel: 'beginner',
    tags: ['Fresh Graduate', 'Backend', 'Laravel', 'MySQL', 'REST API'],
    url: 'https://www.jobstreet.co.id/id/backend-developer-jobs/in-Indonesia',
    sourcePortal: 'JobStreet Indonesia',
    description: 'Kesempatan fresh graduate untuk membangun modul backend, endpoint CRUD, validasi request, dan dokumentasi API.',
    requiredSkills: ['PHP', 'Laravel', 'MySQL', 'REST API', 'Git'],
    publishedDaysAgo: 6,
  },
  {
    id: 'indo-sample-5',
    title: 'Frontend Developer Intern',
    company: 'Pixel Belajar Studio',
    location: 'Yogyakarta, Indonesia',
    workMode: 'hybrid',
    type: 'internship',
    experienceLevel: 'internship',
    tags: ['React', 'TypeScript', 'Tailwind', 'Magang', 'Frontend'],
    url: 'https://glints.com/id/opportunities/jobs/explore?keyword=frontend%20developer%20intern',
    sourcePortal: 'Glints',
    description: 'Magang frontend untuk membangun UI dashboard, memperbaiki responsive layout, dan menulis komponen React yang reusable.',
    requiredSkills: ['HTML', 'CSS', 'JavaScript', 'React', 'Tailwind', 'Git'],
    publishedDaysAgo: 3,
  },
  {
    id: 'indo-sample-6',
    title: 'Junior Frontend Engineer',
    company: 'Kodingin Aja',
    location: 'Surabaya, Indonesia',
    workMode: 'onsite',
    type: 'full-time',
    experienceLevel: 'junior',
    tags: ['React', 'Next.js', 'TypeScript', 'Junior', 'Frontend'],
    url: 'https://www.dealls.com/jobs?search=frontend%20developer',
    sourcePortal: 'Dealls',
    description: 'Junior frontend role untuk mengembangkan halaman produk, loading state, form, dan integrasi REST API dengan Next.js.',
    requiredSkills: ['React', 'Next.js', 'TypeScript', 'REST API', 'CSS'],
    publishedDaysAgo: 7,
  },
  {
    id: 'indo-sample-7',
    title: 'Frontend Web Developer - Fresh Graduate',
    company: 'Mitra Edukasi Digital',
    location: 'Remote Indonesia',
    workMode: 'remote',
    type: 'full-time',
    experienceLevel: 'beginner',
    tags: ['Fresh Graduate', 'React', 'CSS', 'Frontend', 'Remote'],
    url: 'https://www.kitalulus.com/jobs?keyword=frontend%20developer',
    sourcePortal: 'KitaLulus',
    description: 'Role fresh graduate untuk membuat tampilan web edukasi, memperbaiki aksesibilitas, dan menghubungkan UI ke API.',
    requiredSkills: ['HTML', 'CSS', 'JavaScript', 'React', 'Accessibility'],
    publishedDaysAgo: 9,
  },
  {
    id: 'indo-sample-8',
    title: 'Fullstack Developer Intern',
    company: 'Tumbuh Teknologi Nusantara',
    location: 'Jakarta, Indonesia',
    workMode: 'hybrid',
    type: 'internship',
    experienceLevel: 'internship',
    tags: ['Fullstack', 'Next.js', 'Node.js', 'PostgreSQL', 'Magang'],
    url: 'https://www.linkedin.com/jobs/search/?keywords=fullstack%20developer%20intern&location=Indonesia',
    sourcePortal: 'LinkedIn Jobs',
    description: 'Internship fullstack untuk membangun fitur dari UI sampai API, termasuk auth, database, dan deployment checklist.',
    requiredSkills: ['React', 'Next.js', 'Node.js', 'PostgreSQL', 'Git'],
    publishedDaysAgo: 4,
  },
  {
    id: 'indo-sample-9',
    title: 'Junior Fullstack Engineer',
    company: 'Awan Retail Teknologi',
    location: 'Bandung, Indonesia',
    workMode: 'hybrid',
    type: 'full-time',
    experienceLevel: 'junior',
    tags: ['Fullstack', 'React', 'Express', 'PostgreSQL', 'Junior'],
    url: 'https://www.kalibrr.id/job-board/te/fullstack-developer/jobs',
    sourcePortal: 'Kalibrr',
    description: 'Junior engineer untuk membangun dashboard internal, endpoint transaksi, dan reporting sederhana.',
    requiredSkills: ['React', 'Node.js', 'Express', 'PostgreSQL', 'REST API'],
    publishedDaysAgo: 8,
  },
  {
    id: 'indo-sample-10',
    title: 'Software Engineer Fresh Graduate Program',
    company: 'Garuda Fintech Lab',
    location: 'Jakarta, Indonesia',
    workMode: 'onsite',
    type: 'full-time',
    experienceLevel: 'beginner',
    tags: ['Fresh Graduate', 'Software Engineer', 'Backend', 'Frontend'],
    url: 'https://www.jobstreet.co.id/id/software-engineer-fresh-graduate-jobs/in-Indonesia',
    sourcePortal: 'JobStreet Indonesia',
    description: 'Graduate development program untuk belajar engineering practice, code review, testing, API, dan frontend delivery.',
    requiredSkills: ['JavaScript', 'SQL', 'Git', 'Testing', 'REST API'],
    publishedDaysAgo: 10,
  },
  {
    id: 'indo-sample-11',
    title: 'Part-time Web Developer Intern',
    company: 'Kampus Kode Mandiri',
    location: 'Remote Indonesia',
    workMode: 'remote',
    type: 'part-time',
    experienceLevel: 'internship',
    tags: ['Part-time', 'Internship', 'React', 'WordPress', 'Remote'],
    url: 'https://karir.com/search?q=web%20developer%20intern',
    sourcePortal: 'Karir.com',
    description: 'Part-time internship untuk mahasiswa yang ingin membuat landing page, komponen UI, dan integrasi formulir sederhana.',
    requiredSkills: ['HTML', 'CSS', 'JavaScript', 'React', 'Git'],
    publishedDaysAgo: 11,
  },
  {
    id: 'indo-sample-12',
    title: 'Backend API Developer - Entry Level',
    company: 'Sehatin Digital Indonesia',
    location: 'Jakarta, Indonesia',
    workMode: 'hybrid',
    type: 'full-time',
    experienceLevel: 'junior',
    tags: ['Entry Level', 'Backend', 'API', 'PostgreSQL', 'Node.js'],
    url: 'https://id.indeed.com/jobs?q=backend+developer+entry+level&l=Indonesia',
    sourcePortal: 'Indeed Indonesia',
    description: 'Entry level backend role untuk API kesehatan digital, validasi input, query PostgreSQL, dan dokumentasi endpoint.',
    requiredSkills: ['Node.js', 'PostgreSQL', 'Validation', 'REST API', 'Git'],
    publishedDaysAgo: 12,
  },
  {
    id: 'indo-sample-13',
    title: 'MSIB Software Engineer Intern',
    company: 'Partner Kampus Merdeka',
    location: 'Jakarta, Indonesia',
    workMode: 'hybrid',
    type: 'internship',
    experienceLevel: 'internship',
    tags: ['MSIB', 'Magang', 'Software Engineer', 'React', 'Backend'],
    url: 'https://kampusmerdeka.kemdikbud.go.id/program/magang',
    sourcePortal: 'Kampus Merdeka',
    description: 'Reference entry for MSIB-style internship. Users should verify active batches and partner openings on the official Kampus Merdeka portal.',
    requiredSkills: ['Git', 'JavaScript', 'React', 'REST API', 'SQL'],
    publishedDaysAgo: 14,
  },
  {
    id: 'indo-sample-14',
    title: 'Junior React Developer',
    company: 'Cipta Produk Digital',
    location: 'Tangerang, Indonesia',
    workMode: 'onsite',
    type: 'full-time',
    experienceLevel: 'junior',
    tags: ['React', 'TypeScript', 'Frontend', 'Junior', 'Tailwind'],
    url: 'https://www.techinasia.com/jobs/search?keyword=react%20developer&country_name[]=Indonesia',
    sourcePortal: 'Tech in Asia Jobs',
    description: 'Junior React role untuk produk SaaS lokal dengan fokus pada component quality, API integration, and responsive states.',
    requiredSkills: ['React', 'TypeScript', 'Tailwind', 'REST API', 'Testing'],
    publishedDaysAgo: 13,
  },
  {
    id: 'indo-sample-15',
    title: 'Junior Node.js Developer',
    company: 'Peta Bisnis Indonesia',
    location: 'Remote Indonesia',
    workMode: 'remote',
    type: 'full-time',
    experienceLevel: 'junior',
    tags: ['Node.js', 'Express', 'PostgreSQL', 'Remote', 'Junior'],
    url: 'https://www.dealls.com/jobs?search=node.js%20developer',
    sourcePortal: 'Dealls',
    description: 'Junior backend role untuk membangun API, background task sederhana, dan integrasi database untuk produk business intelligence.',
    requiredSkills: ['Node.js', 'Express', 'PostgreSQL', 'REST API', 'Git'],
    publishedDaysAgo: 15,
  },
  {
    id: 'indo-sample-16',
    title: 'QA Automation Intern for Web Apps',
    company: 'Uji Kode Digital',
    location: 'Bandung, Indonesia',
    workMode: 'hybrid',
    type: 'internship',
    experienceLevel: 'internship',
    tags: ['Testing', 'Playwright', 'JavaScript', 'Internship', 'QA'],
    url: 'https://glints.com/id/opportunities/jobs/explore?keyword=qa%20automation%20intern',
    sourcePortal: 'Glints',
    description: 'Internship untuk belajar automated testing, bug reports, regression checks, dan basic frontend debugging.',
    requiredSkills: ['JavaScript', 'Testing', 'Playwright', 'Git', 'Bug Reporting'],
    publishedDaysAgo: 16,
  },
  {
    id: 'indo-sample-17',
    title: 'UI Engineer Intern',
    company: 'Studio Aksesibilitas Web',
    location: 'Yogyakarta, Indonesia',
    workMode: 'hybrid',
    type: 'internship',
    experienceLevel: 'internship',
    tags: ['UI Engineer', 'Accessibility', 'React', 'CSS', 'Magang'],
    url: 'https://www.kalibrr.id/job-board/te/ui-engineer/jobs',
    sourcePortal: 'Kalibrr',
    description: 'Magang UI engineer untuk memperbaiki komponen, keyboard navigation, semantic HTML, dan visual regression checklist.',
    requiredSkills: ['HTML', 'CSS', 'React', 'Accessibility', 'Figma'],
    publishedDaysAgo: 17,
  },
  {
    id: 'indo-sample-18',
    title: 'Mobile Developer Intern',
    company: 'Aplikasi Warga Nusantara',
    location: 'Jakarta, Indonesia',
    workMode: 'onsite',
    type: 'internship',
    experienceLevel: 'internship',
    tags: ['React Native', 'Mobile', 'Internship', 'REST API'],
    url: 'https://www.jobstreet.co.id/id/mobile-developer-intern-jobs/in-Indonesia',
    sourcePortal: 'JobStreet Indonesia',
    description: 'Internship mobile untuk membantu fitur React Native, API integration, testing device, dan release checklist.',
    requiredSkills: ['JavaScript', 'React Native', 'REST API', 'Git', 'Mobile UI'],
    publishedDaysAgo: 18,
  },
  {
    id: 'indo-sample-19',
    title: 'Data Analyst Intern',
    company: 'Analitika Pasar Indonesia',
    location: 'Remote Indonesia',
    workMode: 'remote',
    type: 'internship',
    experienceLevel: 'internship',
    tags: ['Data Analyst', 'SQL', 'Python', 'Dashboard', 'Magang'],
    url: 'https://www.kitalulus.com/jobs?keyword=data%20analyst%20intern',
    sourcePortal: 'KitaLulus',
    description: 'Magang data analyst untuk membersihkan data, query SQL, membuat dashboard, dan menulis insight mingguan.',
    requiredSkills: ['SQL', 'Python', 'Spreadsheet', 'Data Visualization', 'Communication'],
    publishedDaysAgo: 19,
  },
  {
    id: 'indo-sample-20',
    title: 'Junior Supabase Developer',
    company: 'SaaS Lokal Mandiri',
    location: 'Remote Indonesia',
    workMode: 'remote',
    type: 'contract',
    experienceLevel: 'junior',
    tags: ['Supabase', 'PostgreSQL', 'Next.js', 'Auth', 'Remote'],
    url: 'https://www.linkedin.com/jobs/search/?keywords=supabase%20developer&location=Indonesia',
    sourcePortal: 'LinkedIn Jobs',
    description: 'Contract junior untuk membantu Next.js app dengan Supabase Auth, Row Level Security checks, dan dashboard data states.',
    requiredSkills: ['Supabase', 'PostgreSQL', 'Next.js', 'TypeScript', 'Auth'],
    publishedDaysAgo: 20,
  },
  {
    id: 'indo-sample-21',
    title: 'Junior Laravel Backend Developer',
    company: 'Niaga Digital Nusantara',
    location: 'Surabaya, Indonesia',
    workMode: 'onsite',
    type: 'full-time',
    experienceLevel: 'junior',
    tags: ['Laravel', 'Backend', 'MySQL', 'API', 'Junior'],
    url: 'https://karir.com/search?q=laravel%20backend%20developer',
    sourcePortal: 'Karir.com',
    description: 'Junior backend role untuk modul e-commerce, validasi request, queue sederhana, dan laporan operasional.',
    requiredSkills: ['PHP', 'Laravel', 'MySQL', 'REST API', 'Git'],
    publishedDaysAgo: 21,
  },
  {
    id: 'indo-sample-22',
    title: 'Frontend Developer Part-time',
    company: 'Komunitas Produk Belajar',
    location: 'Remote Indonesia',
    workMode: 'remote',
    type: 'part-time',
    experienceLevel: 'junior',
    tags: ['Part-time', 'Frontend', 'React', 'Tailwind', 'Remote'],
    url: 'https://id.indeed.com/jobs?q=part+time+frontend+developer&l=Indonesia',
    sourcePortal: 'Indeed Indonesia',
    description: 'Part-time frontend role untuk memperbaiki pages, reusable components, and loading or empty states for an education product.',
    requiredSkills: ['React', 'Tailwind', 'JavaScript', 'REST API', 'Responsive Design'],
    publishedDaysAgo: 22,
  },
  {
    id: 'indo-sample-23',
    title: 'Graduate Fullstack Engineer',
    company: 'Solusi UMKM Digital',
    location: 'Semarang, Indonesia',
    workMode: 'hybrid',
    type: 'full-time',
    experienceLevel: 'beginner',
    tags: ['Fresh Graduate', 'Fullstack', 'React', 'Node.js', 'PostgreSQL'],
    url: 'https://www.dealls.com/jobs?search=fresh%20graduate%20software%20engineer',
    sourcePortal: 'Dealls',
    description: 'Fresh graduate role for product features across frontend pages, API endpoints, database queries, and deployment notes.',
    requiredSkills: ['React', 'Node.js', 'PostgreSQL', 'TypeScript', 'Git'],
    publishedDaysAgo: 23,
  },
  {
    id: 'indo-sample-24',
    title: 'Backend Developer Apprentice',
    company: 'Bina Sistem Indonesia',
    location: 'Makassar, Indonesia',
    workMode: 'hybrid',
    type: 'internship',
    experienceLevel: 'internship',
    tags: ['Apprentice', 'Backend', 'Node.js', 'Database', 'Magang'],
    url: 'https://glints.com/id/opportunities/jobs/explore?keyword=backend%20developer%20magang',
    sourcePortal: 'Glints',
    description: 'Apprenticeship backend untuk belajar endpoint design, SQL basics, authentication flow, and API troubleshooting.',
    requiredSkills: ['JavaScript', 'Node.js', 'SQL', 'REST API', 'Git'],
    publishedDaysAgo: 24,
  },
]

function daysAgoIso(daysAgo: number) {
  const date = new Date()
  date.setDate(date.getDate() - daysAgo)
  return date.toISOString()
}

export const indonesiaSampleAdapter: JobSourceAdapter = {
  name: 'Indonesia Curated Sample Data',
  slug: 'indonesia-sample',
  type: 'api',
  region: 'indonesia',
  baseUrl: 'https://glints.com/id',
  attributionLabel: 'Indonesia Curated Sample',
  attributionUrl: 'https://glints.com/id/opportunities/jobs/explore',

  isConfigured(): boolean {
    return true
  },

  async fetch(): Promise<Partial<JobPost>[]> {
    return INDONESIA_SAMPLE_JOBS
      .map((job) => this.normalize(job))
      .filter(Boolean) as Partial<JobPost>[]
  },

  normalize(raw: unknown): Partial<JobPost> | null {
    if (!raw || typeof raw !== 'object') return null

    const job = raw as IndonesiaSampleJob
    const publishedAt = daysAgoIso(job.publishedDaysAgo)

    return {
      id: job.id,
      sourceSlug: 'indonesia-sample',
      externalId: job.id,
      title: job.title,
      company: job.company,
      location: job.location,
      country: 'Indonesia',
      regionType: 'indonesia',
      workMode: job.workMode,
      employmentType: job.type,
      experienceLevel: job.experienceLevel,
      description: job.description,
      applyUrl: job.url,
      sourceUrl: job.url,
      tags: job.tags,
      requiredSkills: job.requiredSkills,
      publishedAt,
      fetchedAt: new Date().toISOString(),
      validityScore: 76,
      riskLevel: 'low',
      moderationStatus: 'approved',
      moderationReasons: [
        'Curated Indonesia sample data',
        `Reference portal: ${job.sourcePortal}`,
      ],
      rawPayload: {
        sourcePortal: job.sourcePortal,
        seedType: 'curated-indonesia-entry-level',
      },
    }
  },
}
