import { Skill, SkillCategory, TargetRole } from '@/types'

export const SKILLS: Skill[] = [
  // Frontend Skills
  {
    id: 'skill-html',
    name: 'HTML',
    slug: 'html',
    category: 'frontend',
    roleTags: ['frontend-developer', 'fullstack-developer', 'ui-engineer'],
    priorityWeight: 4,
    description: 'Semantic HTML structure and accessibility',
  },
  {
    id: 'skill-css',
    name: 'CSS',
    slug: 'css',
    category: 'frontend',
    roleTags: ['frontend-developer', 'fullstack-developer', 'ui-engineer'],
    priorityWeight: 4,
    description: 'Styling, layouts, animations, and responsive design',
  },
  {
    id: 'skill-javascript',
    name: 'JavaScript',
    slug: 'javascript',
    category: 'frontend',
    roleTags: ['frontend-developer', 'fullstack-developer', 'ui-engineer', 'mobile-developer'],
    priorityWeight: 5,
    description: 'Core JavaScript language and DOM manipulation',
  },
  {
    id: 'skill-typescript',
    name: 'TypeScript',
    slug: 'typescript',
    category: 'frontend',
    roleTags: ['frontend-developer', 'fullstack-developer', 'ui-engineer', 'mobile-developer'],
    priorityWeight: 4,
    description: 'Type-safe JavaScript superset',
  },
  {
    id: 'skill-react',
    name: 'React',
    slug: 'react',
    category: 'frontend',
    roleTags: ['frontend-developer', 'fullstack-developer', 'ui-engineer'],
    priorityWeight: 5,
    description: 'Component-based UI library',
  },
  {
    id: 'skill-nextjs',
    name: 'Next.js',
    slug: 'nextjs',
    category: 'frontend',
    roleTags: ['frontend-developer', 'fullstack-developer'],
    priorityWeight: 4,
    description: 'React framework with SSR and routing',
  },
  {
    id: 'skill-tailwind',
    name: 'Tailwind CSS',
    slug: 'tailwind',
    category: 'frontend',
    roleTags: ['frontend-developer', 'fullstack-developer', 'ui-engineer'],
    priorityWeight: 3,
    description: 'Utility-first CSS framework',
  },
  {
    id: 'skill-responsive',
    name: 'Responsive Design',
    slug: 'responsive-design',
    category: 'frontend',
    roleTags: ['frontend-developer', 'fullstack-developer', 'ui-engineer'],
    priorityWeight: 4,
    description: 'Mobile-first responsive layouts',
  },
  {
    id: 'skill-rest-api',
    name: 'REST API',
    slug: 'rest-api',
    category: 'frontend',
    roleTags: ['frontend-developer', 'fullstack-developer', 'backend-developer'],
    priorityWeight: 4,
    description: 'API consumption and integration',
  },
  {
    id: 'skill-state-management',
    name: 'State Management',
    slug: 'state-management',
    category: 'frontend',
    roleTags: ['frontend-developer', 'fullstack-developer'],
    priorityWeight: 3,
    description: 'Application state handling (Zustand, Context, Redux)',
  },
  {
    id: 'skill-testing',
    name: 'Testing',
    slug: 'testing',
    category: 'frontend',
    roleTags: ['frontend-developer', 'fullstack-developer', 'backend-developer'],
    priorityWeight: 3,
    description: 'Unit testing, integration testing (Jest, React Testing Library)',
  },
  {
    id: 'skill-git',
    name: 'Git',
    slug: 'git',
    category: 'general',
    roleTags: ['frontend-developer', 'backend-developer', 'fullstack-developer', 'ui-engineer', 'mobile-developer'],
    priorityWeight: 4,
    description: 'Version control and collaboration',
  },
  {
    id: 'skill-deployment',
    name: 'Deployment',
    slug: 'deployment',
    category: 'frontend',
    roleTags: ['frontend-developer', 'fullstack-developer'],
    priorityWeight: 2,
    description: 'Vercel, Netlify, Docker deployment',
  },
  {
    id: 'skill-ui-ux',
    name: 'UI/UX Basic',
    slug: 'ui-ux-basic',
    category: 'frontend',
    roleTags: ['frontend-developer', 'ui-engineer'],
    priorityWeight: 3,
    description: 'Basic design principles and Figma',
  },
  {
    id: 'skill-accessibility',
    name: 'Accessibility',
    slug: 'accessibility',
    category: 'frontend',
    roleTags: ['frontend-developer', 'ui-engineer'],
    priorityWeight: 2,
    description: 'WCAG guidelines and screen reader support',
  },
  {
    id: 'skill-performance',
    name: 'Performance Optimization',
    slug: 'performance',
    category: 'frontend',
    roleTags: ['frontend-developer', 'ui-engineer'],
    priorityWeight: 2,
    description: 'Core Web Vitals, lazy loading, caching',
  },

  // Backend Skills
  {
    id: 'skill-nodejs',
    name: 'Node.js',
    slug: 'nodejs',
    category: 'backend',
    roleTags: ['backend-developer', 'fullstack-developer'],
    priorityWeight: 5,
    description: 'JavaScript runtime for server-side',
  },
  {
    id: 'skill-express',
    name: 'Express',
    slug: 'express',
    category: 'backend',
    roleTags: ['backend-developer', 'fullstack-developer'],
    priorityWeight: 4,
    description: 'Node.js web framework',
  },
  {
    id: 'skill-laravel',
    name: 'Laravel',
    slug: 'laravel',
    category: 'backend',
    roleTags: ['backend-developer'],
    priorityWeight: 4,
    description: 'PHP framework for web applications',
  },
  {
    id: 'skill-database',
    name: 'Database Design',
    slug: 'database-design',
    category: 'backend',
    roleTags: ['backend-developer', 'fullstack-developer', 'data-analyst'],
    priorityWeight: 4,
    description: 'Schema design, relationships, normalization',
  },
  {
    id: 'skill-postgresql',
    name: 'PostgreSQL',
    slug: 'postgresql',
    category: 'backend',
    roleTags: ['backend-developer', 'fullstack-developer', 'data-analyst'],
    priorityWeight: 4,
    description: 'Relational database management',
  },
  {
    id: 'skill-auth',
    name: 'Authentication',
    slug: 'authentication',
    category: 'backend',
    roleTags: ['backend-developer', 'fullstack-developer'],
    priorityWeight: 4,
    description: 'JWT, OAuth, session management',
  },
  {
    id: 'skill-authorization',
    name: 'Authorization',
    slug: 'authorization',
    category: 'backend',
    roleTags: ['backend-developer', 'fullstack-developer'],
    priorityWeight: 3,
    description: 'RBAC, permissions, access control',
  },
  {
    id: 'skill-validation',
    name: 'Validation',
    slug: 'validation',
    category: 'backend',
    roleTags: ['backend-developer', 'fullstack-developer'],
    priorityWeight: 3,
    description: 'Input validation and sanitization',
  },
  {
    id: 'skill-security',
    name: 'Security Basic',
    slug: 'security-basic',
    category: 'backend',
    roleTags: ['backend-developer', 'fullstack-developer'],
    priorityWeight: 3,
    description: 'HTTPS, CORS, rate limiting, SQL injection prevention',
  },
  {
    id: 'skill-api-docs',
    name: 'API Documentation',
    slug: 'api-documentation',
    category: 'backend',
    roleTags: ['backend-developer', 'fullstack-developer'],
    priorityWeight: 2,
    description: 'OpenAPI, Swagger, Postman',
  },

  // General Skills
  {
    id: 'skill-github',
    name: 'GitHub',
    slug: 'github',
    category: 'general',
    roleTags: ['frontend-developer', 'backend-developer', 'fullstack-developer', 'ui-engineer', 'mobile-developer'],
    priorityWeight: 4,
    description: 'GitHub workflows, PRs, actions',
  },
  {
    id: 'skill-problem-solving',
    name: 'Problem Solving',
    slug: 'problem-solving',
    category: 'general',
    roleTags: ['frontend-developer', 'backend-developer', 'fullstack-developer', 'data-analyst'],
    priorityWeight: 5,
    description: 'Debugging and logical thinking',
  },
  {
    id: 'skill-debugging',
    name: 'Debugging',
    slug: 'debugging',
    category: 'general',
    roleTags: ['frontend-developer', 'backend-developer', 'fullstack-developer'],
    priorityWeight: 4,
    description: 'Browser DevTools, error tracking',
  },
  {
    id: 'skill-documentation',
    name: 'Documentation',
    slug: 'documentation',
    category: 'general',
    roleTags: ['frontend-developer', 'backend-developer', 'fullstack-developer'],
    priorityWeight: 2,
    description: 'Code documentation, README writing',
  },
  {
    id: 'skill-communication',
    name: 'Communication',
    slug: 'communication',
    category: 'general',
    roleTags: ['frontend-developer', 'backend-developer', 'fullstack-developer'],
    priorityWeight: 3,
    description: 'Team collaboration and documentation',
  },
  {
    id: 'skill-project-management',
    name: 'Project Management',
    slug: 'project-management',
    category: 'general',
    roleTags: ['frontend-developer', 'backend-developer', 'fullstack-developer'],
    priorityWeight: 2,
    description: 'Agile, Scrum, task tracking',
  },
]

export const SKILL_CATEGORIES: { id: SkillCategory; label: string; color: string }[] = [
  { id: 'frontend', label: 'Frontend', color: 'blue' },
  { id: 'backend', label: 'Backend', color: 'green' },
  { id: 'general', label: 'General', color: 'purple' },
]

export function getSkillsByCategory(category: SkillCategory): Skill[] {
  return SKILLS.filter((skill) => skill.category === category)
}

export function getSkillById(id: string): Skill | undefined {
  return SKILLS.find((skill) => skill.id === id || skill.slug === id)
}

export function getSkillsByRole(role: TargetRole): Skill[] {
  return SKILLS.filter((skill) => skill.roleTags.includes(role))
}

export const SKILL_LEVEL_LABELS: Record<number, string> = {
  0: 'Not learned',
  1: 'Learning',
  2: 'Basic',
  3: 'Project-level',
  4: 'Professional',
}