'use client'

import dynamic from 'next/dynamic'
import { motion, useScroll, useTransform } from 'framer-motion'
import Link from 'next/link'
import { Container } from '@/components/layout'
import { GradientBackground } from '@/components/layout'
import { CartoonBackground } from '@/components/illustrations/cartoon-background'
import { BrutalCard, BrutalCardHover, BrutalButton, FloatingSticker, StickerBadge, ParallaxCard, GlowCard, StarBurst } from '@/components/brutal'
import type { CardColor } from '@/components/brutal/brutal-card'
import { CSSAnimatedScene, use3DSupport } from '@/components/three/css-animated-scene'
import { CatMascot } from '@/components/illustrations/cat-mascot'
import { DoodleBackground } from '@/components/illustrations/doodle-background'
import { useRef } from 'react'
import {
  ArrowRight,
  Target,
  Compass,
  Map,
  Trophy,
  TrendingUp,
  Zap,
  Users,
  Star,
  BookOpen,
  Rocket,
  Swords,
  Sparkles,
  ChevronRight,
} from 'lucide-react'
import { cn } from '@/lib/utils'

const ThreeFloatingScene = dynamic(
  () => import('@/components/three/floating-scene').then((mod) => mod.ThreeFloatingScene),
  {
    ssr: false,
    loading: () => <CSSAnimatedScene className="h-80 lg:h-96" />,
  }
)

const features = [
  {
    icon: Target,
    title: 'Skill Gap Analyzer',
    description: 'Compare your current skills with real job requirements and see exactly what you are missing.',
    color: 'yellow' as const,
    sticker: 'scanner',
  },
  {
    icon: Compass,
    title: 'Job Radar',
    description: 'Find remote jobs that match your skill level. No more applying to positions you are not ready for.',
    color: 'blue' as const,
    sticker: 'radar',
  },
  {
    icon: Map,
    title: 'AI Roadmap',
    description: 'Get a personalized learning roadmap generated by AI based on your goals and missing skills.',
    color: 'pink' as const,
    sticker: 'treasure',
  },
  {
    icon: Trophy,
    title: 'GitHub Portfolio',
    description: 'Analyze your GitHub profile and get actionable suggestions to improve your portfolio.',
    color: 'green' as const,
    sticker: 'trophy',
  },
  {
    icon: TrendingUp,
    title: 'Project Review',
    description: 'Submit mini and final projects with rule-based checks and AI-assisted feedback.',
    color: 'orange' as const,
    sticker: 'review',
  },
  {
    icon: Zap,
    title: 'Quiz Challenges',
    description: 'Lock task completion behind real quizzes so your progress reflects actual mastery.',
    color: 'purple' as const,
    sticker: 'battle',
  },
]

const steps = [
  {
    number: 1,
    icon: Rocket,
    title: 'Choose Your Path',
    description: 'Select the developer role you want to pursue: Frontend, Backend, Fullstack, and more.',
    badge: 'Start Quest',
  },
  {
    number: 2,
    icon: BookOpen,
    title: 'Map Your Skills',
    description: 'Rate your current skill levels from 0 to 4. This shapes your unique adventure.',
    badge: 'Level Up',
  },
  {
    number: 3,
    icon: Target,
    title: 'Find Your Missions',
    description: 'Discover jobs that match your current power level. No more impossible bosses!',
    badge: 'Missions',
  },
  {
    number: 4,
    icon: Map,
    title: 'Follow Your Roadmap',
    description: 'Get an AI-generated learning path with weekly quests and mini-projects.',
    badge: 'Quests',
  },
  {
    number: 5,
    icon: Swords,
    title: 'Level Up & Win',
    description: 'Complete weekly sprints, pass quizzes, ship projects, and watch your score climb.',
    badge: 'Victory',
  },
]

export default function HomePage() {
  const use3D = use3DSupport()

  return (
    <div className="min-h-screen relative overflow-hidden">
      <CartoonBackground variant="default" intensity="high" showDoodles animated />
      <GradientBackground />

      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-background/90 backdrop-blur-sm border-b-3 border-black">
        <Container className="flex items-center justify-between py-4">
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            className="flex items-center gap-3"
          >
            <div className="w-12 h-12 bg-yellow brutal-border brutal-radius flex items-center justify-center shadow-brutal-sm hover:shadow-brutal transition-all">
              <Target className="w-7 h-7" />
            </div>
            <div>
              <span className="font-display font-bold text-xl block">SkillPath</span>
              <span className="text-[10px] text-black/50 font-medium">Career OS</span>
            </div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            className="flex items-center gap-3"
          >
            <Link href="/login">
              <BrutalButton variant="ghost" size="sm">
                Sign In
              </BrutalButton>
            </Link>
            <Link href="/register">
              <BrutalButton color="yellow" size="sm" className="shadow-brutal-sm hover:shadow-brutal">
                Start Free
              </BrutalButton>
            </Link>
          </motion.div>
        </Container>
      </nav>

      {/* Hero Section - Quest Theme */}
      <section className="pt-28 pb-16 px-4 relative overflow-hidden">
        {/* Background glow effects */}
        <div className="absolute top-0 left-1/4 w-96 h-96 bg-yellow/20 rounded-full blur-3xl -z-10" />
        <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-pink/20 rounded-full blur-3xl -z-10" />

        <Container className="relative z-10">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <ParallaxCard speed={0.3} className="relative">
              <motion.div
                initial={{ opacity: 0, y: 30 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6 }}
              >
                {/* Quest Badge with animation */}
                <motion.div
                  className="inline-flex items-center gap-2 bg-yellow brutal-border brutal-radius px-5 py-2.5 mb-6 shadow-brutal-sm cursor-pointer"
                  whileHover={{ scale: 1.05, rotate: -1 }}
                  whileTap={{ scale: 0.95 }}
                >
                  <motion.div
                    animate={{ rotate: [0, 10, -10, 0] }}
                    transition={{ duration: 1, repeat: Infinity }}
                  >
                    <Sparkles className="w-5 h-5" />
                  </motion.div>
                  <span className="text-sm font-bold">Your Developer Career Quest</span>
                </motion.div>

                {/* Main Title with 3D effect */}
                <motion.h1
                  className="font-display font-black text-4xl sm:text-5xl lg:text-6xl leading-tight mb-6"
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.1 }}
                >
                  Build your{' '}
                  <span className="relative inline-block">
                    <span className="relative z-10 bg-yellow px-4 py-2 inline-block">developer career</span>
                    <span className="absolute bottom-0 left-0 right-0 h-4 bg-black -z-0" />
                  </span>{' '}
                  <motion.span
                    className="relative inline-block"
                    whileHover={{ scale: 1.05 }}
                  >
                    <span className="relative z-10 bg-pink px-4 py-2 inline-block">like a quest.</span>
                    <span className="absolute bottom-0 left-0 right-0 h-4 bg-black -z-0" />
                  </motion.span>
                </motion.h1>

                <motion.p
                  className="text-lg sm:text-xl text-gray-700 mb-8 max-w-lg"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ delay: 0.2 }}
                >
                  SkillPath is your career game OS. Check skills, unlock quests, level up, and land your dream developer job.
                </motion.p>

                {/* Quest CTA with glow effect */}
                <motion.div
                  className="flex flex-col sm:flex-row gap-4 mb-8"
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.3 }}
                >
                  <GlowCard color="yellow" className="rounded-brutal">
                    <Link href="/register">
                      <BrutalButton color="yellow" size="lg" className="w-full sm:w-auto shadow-brutal hover:shadow-brutal-lg transition-all">
                        <Rocket className="w-5 h-5 mr-2" />
                        Start Your Path
                      </BrutalButton>
                    </Link>
                  </GlowCard>
                  <Link href="/dashboard">
                    <BrutalButton variant="outline" color="black" size="lg" className="w-full sm:w-auto">
                      <Map className="w-5 h-5 mr-2" />
                      View Demo
                    </BrutalButton>
                  </Link>
                </motion.div>

                {/* Mascot Speech Bubble with bounce */}
                <motion.div
                  initial={{ opacity: 0, scale: 0.8 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ delay: 0.5, type: 'spring', stiffness: 200 }}
                  className="flex items-center gap-4"
                >
                  <motion.div
                    className="w-20 h-20 bg-yellow brutal-border brutal-radius flex items-center justify-center shadow-brutal-sm"
                    animate={{ y: [0, -5, 0] }}
                    transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut' }}
                  >
                    <span className="text-4xl">🐱</span>
                  </motion.div>
                  <div className="relative rounded-brutal border-3 border-black bg-white px-6 py-4 shadow-brutal">
                    <div className="absolute -left-4 top-6 h-4 w-4 rotate-45 border-b-3 border-l-3 border-black bg-white" />
                    <motion.p
                      className="font-display font-bold text-lg"
                      animate={{ scale: [1, 1.02, 1] }}
                      transition={{ duration: 2, repeat: Infinity }}
                    >
                      Ready to start your quest?
                    </motion.p>
                    <p className="text-sm text-black/60">Your roadmap is waiting!</p>
                  </div>
                </motion.div>
              </motion.div>
            </ParallaxCard>

            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.6, delay: 0.2 }}
              className="relative"
            >
              {use3D ? (
                <ThreeFloatingScene className="h-80 lg:h-96" />
              ) : (
                <CSSAnimatedScene className="h-80 lg:h-96" />
              )}

              {/* Enhanced Floating stickers with animations */}
              <motion.div
                className="absolute top-0 right-4"
                animate={{ y: [0, -15, 0], rotate: [0, 5, 0] }}
                transition={{ duration: 3, repeat: Infinity }}
              >
                <FloatingSticker icon="badge" color="yellow" size="md" />
              </motion.div>
              <motion.div
                className="absolute bottom-8 left-0"
                animate={{ y: [0, -20, 0], rotate: [0, -5, 0] }}
                transition={{ duration: 4, repeat: Infinity, delay: 0.5 }}
              >
                <FloatingSticker icon="rocket" color="pink" size="sm" />
              </motion.div>
              <motion.div
                className="absolute top-16 left-0"
                animate={{ y: [0, -10, 0] }}
                transition={{ duration: 5, repeat: Infinity, delay: 1 }}
              >
                <FloatingSticker icon="code" color="blue" size="sm" />
              </motion.div>

              {/* Star burst decoration */}
              <div className="absolute top-8 right-8">
                <StarBurst count={6} color="bg-yellow" />
              </div>

              {/* Floating badges with pulse */}
              <motion.div
                className="absolute -bottom-4 right-6 hidden md:block"
                animate={{ scale: [1, 1.05, 1] }}
                transition={{ duration: 2, repeat: Infinity }}
              >
                <StickerBadge variant="completed" label="Quiz 10/10" size="sm" className="shadow-brutal-sm" />
              </motion.div>
              <div className="absolute top-12 right-2 hidden md:block">
                <div className="bg-yellow brutal-border brutal-radius px-3 py-2 shadow-brutal-sm">
                  <p className="text-xs font-bold">React + TypeScript</p>
                </div>
              </div>

              {/* Decorative corners */}
              <div className="absolute -top-2 -left-2 w-8 h-8 bg-green brutal-border brutal-radius" style={{ borderTopRightRadius: '100%' }} />
              <div className="absolute -bottom-2 -right-2 w-8 h-8 bg-blue brutal-border brutal-radius" style={{ borderTopLeftRadius: '100%' }} />
            </motion.div>
          </div>
        </Container>
      </section>

      {/* Problem Section - Game Style */}
      <section className="py-16 px-4 bg-black text-white relative">
        <Container>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <StickerBadge variant="boss-fight" label="Boss Battles" size="lg" className="mb-4" />
            <h2 className="font-display font-bold text-3xl sm:text-4xl mb-4">
              Sound familiar?
            </h2>
            <p className="text-gray-300 max-w-2xl mx-auto">
              Every developer faces these boss battles. SkillPath helps you defeat them.
            </p>
          </motion.div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {[
              { emoji: '🤔', title: 'Skill Boss', text: 'Students do not know which skills actually matter' },
              { emoji: '📄', title: 'Confusion Spell', text: 'Job descriptions are confusing and inconsistent' },
              { emoji: '📚', title: 'No Map Quest', text: 'Tutorials are scattered everywhere, no clear path' },
              { emoji: '💼', title: 'Portfolio Ghost', text: 'Portfolios do not match target roles' },
            ].map((problem, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
              >
                <div className="h-full brutal-border brutal-radius p-6 bg-white/10 backdrop-blur border-white/20">
                  <span className="text-5xl mb-4 block">{problem.emoji}</span>
                  <p className="font-bold text-lg mb-2">{problem.title}</p>
                  <p className="text-sm text-gray-300">{problem.text}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </Container>
      </section>

      {/* How it Works - Quest Path */}
      <section className="py-20 px-4 relative">
        <Container>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <StickerBadge variant="yellow" label="Your Quest" size="lg" className="mb-4" />
            <h2 className="font-display font-bold text-3xl sm:text-4xl mb-4">
              How to Win Your Career Quest
            </h2>
            <p className="text-gray-600 max-w-2xl mx-auto">
              Five epic levels to conquer your developer career.
            </p>
          </motion.div>

          <div className="max-w-3xl mx-auto space-y-6">
            {steps.map((step, i) => (
              <motion.div
                key={step.number}
                initial={{ opacity: 0, x: -20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
              >
                <BrutalCardHover color={['yellow', 'blue', 'pink', 'green', 'orange'][i % 5] as CardColor} className="flex items-start gap-6">
                  <div className="relative">
                    <div className="w-14 h-14 bg-black text-white brutal-border brutal-radius flex items-center justify-center font-bold text-2xl shrink-0">
                      {step.number}
                    </div>
                    <div className="absolute -bottom-1 -right-1 w-7 h-7 bg-yellow brutal-border brutal-radius flex items-center justify-center shadow-brutal-sm">
                      <step.icon className="w-4 h-4" />
                    </div>
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-1">
                      <h3 className="font-display font-bold text-lg">{step.title}</h3>
                      <StickerBadge variant={['yellow', 'blue', 'pink', 'green', 'orange'][i % 5] as any} label={step.badge} size="sm" />
                    </div>
                    <p className="text-gray-600">{step.description}</p>
                  </div>
                </BrutalCardHover>
              </motion.div>
            ))}
          </div>
        </Container>
      </section>

      {/* Features - Power-Ups */}
      <section className="py-20 px-4 bg-cream-light relative">
        <Container>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <StickerBadge variant="green" label="Power-Ups" size="lg" className="mb-4" />
            <h2 className="font-display font-bold text-3xl sm:text-4xl mb-4">
              Your Developer Power-Ups
            </h2>
            <p className="text-gray-600 max-w-2xl mx-auto">
              Collect these power-ups to level up your career.
            </p>
          </motion.div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((feature, i) => (
              <motion.div
                key={feature.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
              >
                <BrutalCard color={feature.color} className="h-full relative overflow-hidden">
                  <div className="absolute top-2 right-2 opacity-20">
                    <feature.icon className="w-20 h-20" />
                  </div>
                  <feature.icon className="w-10 h-10 mb-4 relative z-10" />
                  <h3 className="font-display font-bold text-lg mb-2 relative z-10">{feature.title}</h3>
                  <p className="text-gray-700 text-sm relative z-10">{feature.description}</p>
                </BrutalCard>
              </motion.div>
            ))}
          </div>
        </Container>
      </section>

      {/* Demo Preview - Game Stats */}
      <section className="py-20 px-4">
        <Container>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <StickerBadge variant="pink" label="Live Preview" size="lg" className="mb-4" />
            <h2 className="font-display font-bold text-3xl sm:text-4xl mb-4">
              See Your Stats in Action
            </h2>
            <p className="text-gray-600 max-w-2xl mx-auto">
              A sneak peek at your player dashboard.
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="max-w-4xl mx-auto"
          >
            <BrutalCard shadow="lg" className="p-0 overflow-hidden">
              {/* Dashboard Preview Header */}
              <div className="bg-yellow p-4 border-b-3 border-black">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-4">
                    <div className="w-12 h-12 bg-white brutal-border brutal-radius flex items-center justify-center">
                      <Target className="w-6 h-6" />
                    </div>
                    <div>
                      <p className="font-display font-bold">Your Dashboard</p>
                      <p className="text-sm text-black/70">Player stats updated</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="text-2xl">🐱</span>
                    <StickerBadge variant="completed" label="Level 5" size="sm" />
                  </div>
                </div>
              </div>

              {/* Dashboard Preview Content */}
              <div className="p-6 space-y-6">
                <div className="grid sm:grid-cols-3 gap-4">
                  <BrutalCard color="pink" className="text-center">
                    <p className="text-4xl font-bold mb-1">72%</p>
                    <p className="text-sm font-medium">Career Power</p>
                    <StickerBadge variant="completed" label="Strong" size="sm" className="mt-2" />
                  </BrutalCard>
                  <BrutalCard color="blue" className="text-center">
                    <p className="text-4xl font-bold mb-1">85%</p>
                    <p className="text-sm font-medium">Job Match</p>
                    <StickerBadge variant="great-match" label="Great!" size="sm" className="mt-2" />
                  </BrutalCard>
                  <BrutalCard color="green" className="text-center">
                    <p className="text-4xl font-bold mb-1">5</p>
                    <p className="text-sm font-medium">Day Streak</p>
                    <StickerBadge variant="yellow" label="On Fire!" size="sm" className="mt-2" />
                  </BrutalCard>
                </div>

                <div className="grid sm:grid-cols-2 gap-4">
                  <BrutalCard>
                    <div className="flex items-center gap-2 mb-2">
                      <h4 className="font-bold">Current Quest</h4>
                      <StickerBadge variant="in-progress" label="Active" size="sm" />
                    </div>
                    <p className="text-2xl font-display font-bold text-blue">Frontend Developer</p>
                  </BrutalCard>
                  <BrutalCard>
                    <div className="flex items-center gap-2 mb-2">
                      <h4 className="font-bold">Weekly Mission</h4>
                      <StickerBadge variant="blue" label="3 Left" size="sm" />
                    </div>
                    <p className="text-lg">Build React API Dashboard</p>
                  </BrutalCard>
                </div>

                <div>
                  <h4 className="font-bold mb-3">Missing Power-Ups</h4>
                  <div className="flex flex-wrap gap-2">
                    {['TypeScript', 'Testing', 'API Integration'].map((skill) => (
                      <StickerBadge
                        key={skill}
                        variant="yellow"
                        label={skill}
                        size="sm"
                      />
                    ))}
                  </div>
                </div>
              </div>
            </BrutalCard>
          </motion.div>
        </Container>
      </section>

      {/* CTA Section - Final Quest */}
      <section className="py-20 px-4 bg-yellow relative">
        <Container className="text-center relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <div className="w-20 h-20 bg-white brutal-border brutal-radius flex items-center justify-center mx-auto mb-6 shadow-brutal">
              <span className="text-4xl">🐱</span>
            </div>
            <StickerBadge variant="completed" label="Ready to Start?" size="lg" className="mb-4 inline-block" />
            <h2 className="font-display font-black text-3xl sm:text-4xl mb-4">
              Ready to Start Your Quest?
            </h2>
            <p className="text-black/70 max-w-2xl mx-auto mb-8">
              Join thousands of developers who have used SkillPath to conquer their career. It takes just 5 minutes to begin!
            </p>
            <Link href="/register">
              <BrutalButton color="black" size="lg" className="shadow-brutal hover:shadow-brutal-lg">
                <Rocket className="w-5 h-5 mr-2" />
                Start Your Journey
              </BrutalButton>
            </Link>
          </motion.div>
        </Container>
      </section>

      {/* Footer */}
      <footer className="py-10 px-4 bg-black text-white">
        <Container>
          <div className="flex flex-col sm:flex-row items-center justify-between gap-6">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-yellow brutal-border brutal-radius flex items-center justify-center text-black">
                <Target className="w-6 h-6" />
              </div>
              <span className="font-display font-bold text-xl">SkillPath</span>
            </div>

            <p className="text-gray-400 text-sm text-center">
              Job data powered by{' '}
              <a
                href="https://remotive.com"
                target="_blank"
                rel="noopener noreferrer"
                className="text-yellow hover:underline"
              >
                Remotive
              </a>
            </p>

            <div className="flex gap-6 text-sm">
              <a href="#" className="text-gray-400 hover:text-white transition-colors">
                GitHub
              </a>
              <a href="#" className="text-gray-400 hover:text-white transition-colors">
                Docs
              </a>
              <a href="#" className="text-gray-400 hover:text-white transition-colors">
                Privacy
              </a>
            </div>
          </div>
        </Container>
      </footer>
    </div>
  )
}
