'use client'

import { motion, useReducedMotion, useScroll, type Variants } from 'framer-motion'
import { useState, type ReactNode } from 'react'
import Link from 'next/link'
import { Container } from '@/components/layout'
import { cn } from '@/lib/utils'
import { CartoonBackground } from '@/components/illustrations/cartoon-background'
import { Landing3DBackground } from '@/components/illustrations/landing-3d-background'
import { AnimatedCatMascot } from '@/components/illustrations/animated-cat-mascot'
import {
  BrutalCard,
  BrutalCardHover,
  BrutalButton,
  StickerBadge,
  LevelChip,
  XPBar,
  StatTile,
} from '@/components/brutal'
import { AppWindow, MiniTerminal, JobRadarCard } from '@/components/public'
import type { CardColor } from '@/components/brutal/brutal-card'
import type { StickerBadgeVariant } from '@/components/brutal/brutal-ui-v2'
import {
  Target,
  Compass,
  Map,
  Trophy,
  TrendingUp,
  Zap,
  Rocket,
  Swords,
  Sparkles,
  Flame,
  Play,
  ArrowRight,
  Github,
} from 'lucide-react'

const EASE: [number, number, number, number] = [0.2, 0, 0, 1]

const features = [
  {
    icon: Map,
    title: 'AI Roadmap',
    description: 'A personalized learning roadmap generated by AI from your goals and missing skills.',
    color: 'yellow' as const,
  },
  {
    icon: Compass,
    title: 'Weekly Sprint',
    description: 'Turn your roadmap into focused weekly quests with a clear daily board.',
    color: 'blue' as const,
  },
  {
    icon: Zap,
    title: 'Mini Quiz',
    description: 'Pass focused checks before a task is marked complete.',
    color: 'pink' as const,
  },
  {
    icon: TrendingUp,
    title: 'Project Review',
    description: 'Submit mini and final projects with rule-based checks and AI-assisted feedback.',
    color: 'green' as const,
  },
  {
    icon: Target,
    title: 'Job Radar',
    description: 'Find Indonesia, junior, internship, and fresh-graduate roles that match your profile.',
    color: 'orange' as const,
  },
  {
    icon: Trophy,
    title: 'GitHub Tracker',
    description: 'Analyze your GitHub profile and get actionable portfolio improvements.',
    color: 'purple' as const,
  },
]

const steps = [
  {
    number: 1,
    icon: Rocket,
    title: 'Pick your role',
    description: 'Choose the developer path you want: Frontend, Backend, Fullstack, and more.',
    badge: 'Start Quest',
  },
  {
    number: 2,
    icon: Map,
    title: 'Follow your roadmap',
    description: 'Work through weekly modules, resources, and tasks built for your current level.',
    badge: 'Level Up',
  },
  {
    number: 3,
    icon: Swords,
    title: 'Pass quizzes and projects',
    description: 'Prove progress with mini quizzes and project submissions before moving forward.',
    badge: 'Proof',
  },
  {
    number: 4,
    icon: Target,
    title: 'Apply to matching jobs',
    description: 'Use your skills, role, and level to prioritize realistic junior and internship jobs.',
    badge: 'Missions',
  },
]

const stepBadgeVariants = ['yellow', 'blue', 'pink', 'green'] satisfies StickerBadgeVariant[]

// "Boss battles" = the recurring pains a junior dev hits. Each card is framed as
// an enemy with a threat meter so the dark section reads as a game arena.
const bosses = [
  { emoji: '🤔', title: 'Skill Boss', text: 'Students do not know which skills actually matter.', color: 'bg-pink', threat: '85%' },
  { emoji: '📄', title: 'Confusion Spell', text: 'Job descriptions are confusing and inconsistent.', color: 'bg-blue', threat: '70%' },
  { emoji: '📚', title: 'No Map Quest', text: 'Tutorials are scattered everywhere, with no clear path.', color: 'bg-yellow', threat: '92%' },
  { emoji: '👻', title: 'Portfolio Ghost', text: 'Portfolios do not match the target role.', color: 'bg-orange', threat: '64%' },
] as const

const revealVariants: Variants = {
  hidden: { opacity: 0, y: 20 },
  shown: { opacity: 1, y: 0 },
}

// Scroll-in reveal that is a no-op container under reduced motion.
function Reveal({ children, className, delay = 0 }: { children: ReactNode; className?: string; delay?: number }) {
  const reduce = useReducedMotion()
  if (reduce) return <div className={className}>{children}</div>
  return (
    <motion.div
      className={className}
      variants={revealVariants}
      initial="hidden"
      whileInView="shown"
      viewport={{ once: true, margin: '-80px' }}
      transition={{ duration: 0.5, delay, ease: EASE }}
    >
      {children}
    </motion.div>
  )
}

// Hero "app window" body — a believable career-OS dashboard built only from real
// DOM text + shared HUD primitives (so the window is never the sole info carrier).
function HeroDashboard() {
  return (
    <div className="space-y-4 bg-white p-4 sm:p-5">
      <div className="flex items-center justify-between gap-3">
        <div className="flex min-w-0 items-center gap-2">
          <span
            className="grid h-9 w-9 shrink-0 place-items-center bg-yellow text-lg brutal-border brutal-radius"
            aria-hidden="true"
          >
            🐱
          </span>
          <div className="min-w-0">
            <p className="hud-label text-[10px] text-secondary">Now Playing</p>
            <p className="truncate font-display font-bold leading-tight">Future Dev</p>
          </div>
        </div>
        <LevelChip level={5} />
      </div>

      <XPBar value={1240} max={2000} label="XP to Level 6" accent="yellow" />

      <div className="grid grid-cols-2 gap-3">
        <StatTile label="Career Power" value="72" unit="%" icon={Flame} accent="pink" className="p-4" />
        <StatTile label="Job Match" value="85" unit="%" icon={Target} accent="blue" className="p-4" />
      </div>

      <div className="flex items-center justify-between gap-2 bg-cream-light px-3 py-2 brutal-border brutal-radius">
        <div className="min-w-0">
          <p className="hud-label text-[10px] text-secondary">Current Quest</p>
          <p className="truncate text-sm font-bold">React API Patterns</p>
        </div>
        <StickerBadge variant="in-progress" label="Active" size="sm" />
      </div>

      <div className="space-y-2">
        <XPBar value={80} max={100} label="Roadmap" accent="green" />
        <XPBar value={60} max={100} label="Quizzes" accent="blue" />
        <XPBar value={40} max={100} label="Projects" accent="pink" />
      </div>
    </div>
  )
}

// Landing-only GitHub portfolio tracker preview (illustrative chrome).
function GitHubTrackerCard() {
  const repos = [
    { name: 'portfolio-site', note: 'Add tests + README' },
    { name: 'react-dashboard', note: 'Great structure' },
    { name: 'api-playground', note: 'Pin & document' },
  ]
  return (
    <AppWindow routeTab="SKILLPATH://GITHUB" urlPill="github-tracker" className="h-full">
      <div className="p-5 sm:p-6">
        <div className="mb-4 flex items-center gap-2">
          <span className="grid h-10 w-10 place-items-center bg-purple text-white brutal-border brutal-radius">
            <Github className="h-5 w-5" aria-hidden="true" />
          </span>
          <div className="min-w-0">
            <h3 className="font-display text-heading-sm font-bold leading-tight">GitHub Tracker</h3>
            <p className="text-xs text-secondary">Portfolio readiness &amp; next actions</p>
          </div>
          <span className="ml-auto shrink-0">
            <LevelChip level="68%" label="READY" />
          </span>
        </div>
        <XPBar value={68} max={100} label="Portfolio readiness" accent="green" className="mb-4" />
        <ul className="space-y-2">
          {repos.map((repo) => (
            <li
              key={repo.name}
              className="flex items-center justify-between gap-3 bg-cream-light px-3 py-2 brutal-border brutal-radius"
            >
              <span className="metric-mono truncate text-sm font-bold">{repo.name}</span>
              <span className="truncate text-xs text-secondary">{repo.note}</span>
            </li>
          ))}
        </ul>
      </div>
    </AppWindow>
  )
}

export default function HomePage() {
  const { scrollYProgress } = useScroll()
  const prefersReducedMotion = useReducedMotion()
  const [activeTab, setActiveTab] = useState<'stats' | 'quests'>('stats')

  return (
    <div className="relative min-h-screen overflow-hidden">
      {/* Scroll progress */}
      <motion.div
        className="fixed left-0 right-0 top-0 z-[60] h-2 origin-left border-b-2 border-black bg-pink"
        style={{ scaleX: scrollYProgress }}
        aria-hidden="true"
      />

      {/* Soft paper backdrop; the animated cartoon doodle field lives per-section below. */}
      <CartoonBackground variant="default" intensity="normal" showDoodles={false} animated />

      {/* Navigation */}
      <nav className="fixed left-0 right-0 top-0 z-50 border-b-3 border-black bg-background/90 backdrop-blur-sm">
        <Container className="flex items-center justify-between py-4">
          <Link href="/" className="flex items-center gap-3 rounded-brutal focus-brutal-ring">
            <div className="flex h-12 w-12 items-center justify-center bg-yellow brutal-border brutal-radius shadow-brutal-sm">
              <Sparkles className="h-7 w-7" aria-hidden="true" />
            </div>
            <div>
              <span className="block font-display text-xl font-bold leading-none">SkillPath</span>
              <span className="hud-label text-[10px] text-secondary">Career OS</span>
            </div>
          </Link>

          <div className="flex items-center gap-3">
            <Link href="/login">
              <BrutalButton variant="ghost" size="sm">
                Sign In
              </BrutalButton>
            </Link>
            <Link href="/register">
              <BrutalButton color="yellow" size="sm">
                Start Free
              </BrutalButton>
            </Link>
          </div>
        </Container>
      </nav>

      {/* Hero */}
      <section className="relative overflow-hidden px-4 pb-16 pt-28">
        <Landing3DBackground preset="hero" parallax />
        <Container className="relative z-10">
          <div className="grid items-center gap-12 lg:grid-cols-2">
            <motion.div
              initial={{ opacity: 0, y: 24 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, ease: EASE }}
            >
              <div className="mb-6 inline-flex items-center gap-2 bg-yellow px-4 py-2 brutal-border brutal-radius shadow-brutal-sm">
                <span className="h-2.5 w-2.5 rounded-full border border-black bg-green" aria-hidden="true" />
                <span className="hud-label text-xs">Career OS · Live demo</span>
              </div>

              <h1 className="mb-6 font-display text-4xl font-black leading-tight sm:text-5xl lg:text-6xl">
                Build your{' '}
                <span className="relative inline-block">
                  <span className="relative z-10 inline-block bg-yellow px-3 py-1">developer career</span>
                  <span className="absolute bottom-0 left-0 right-0 -z-0 h-3 bg-black" aria-hidden="true" />
                </span>{' '}
                <span className="relative inline-block">
                  <span className="relative z-10 inline-block bg-pink px-3 py-1">like a quest.</span>
                  <span className="absolute bottom-0 left-0 right-0 -z-0 h-3 bg-black" aria-hidden="true" />
                </span>
              </h1>

              <p className="mb-8 max-w-lg text-body-lg text-secondary">
                Your career, as a console you can actually run. Check your skills, generate a roadmap, clear quests,
                and land your first developer job — with a buddy cheering you on.
              </p>

              <div className="mb-8 flex flex-col gap-4 sm:flex-row">
                <Link href="/register">
                  <BrutalButton color="yellow" size="lg" className="w-full shadow-brutal hover:shadow-brutal-lg sm:w-auto">
                    <Rocket className="h-5 w-5" aria-hidden="true" />
                    Start Your Path
                  </BrutalButton>
                </Link>
                <Link href="/dashboard">
                  <BrutalButton variant="outline" color="black" size="lg" className="w-full sm:w-auto">
                    <Play className="h-5 w-5" aria-hidden="true" />
                    View Demo
                  </BrutalButton>
                </Link>
              </div>

              <div className="flex flex-wrap items-center gap-2">
                <StickerBadge variant="completed" label="Roadmap" size="sm" />
                <StickerBadge variant="in-progress" label="Quizzes" size="sm" />
                <StickerBadge variant="great-match" label="Job Match" size="sm" />
              </div>

              {/* Mobile-only compact preview keeps small screens light but not empty */}
              <div className="mt-8 grid grid-cols-2 gap-3 lg:hidden">
                <StatTile label="Job Match" value="85" unit="%" icon={Target} accent="blue" className="p-4" />
                <StatTile label="Career Power" value="72" unit="%" icon={Flame} accent="pink" className="p-4" />
              </div>
            </motion.div>

            {/* Desktop hero: the career-OS dashboard window + a code terminal */}
            <motion.div
              initial={{ opacity: 0, scale: 0.96 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.5, delay: 0.15, ease: EASE }}
              className="relative hidden lg:block"
            >
              {/* Reactive cat companion (decorative) */}
              <div className="absolute -right-3 -top-9 z-20" aria-hidden="true">
                <AnimatedCatMascot size="sm" mood="cheer" withMessage="Lvl 5!" animated />
              </div>

              <AppWindow routeTab="SKILLPATH://DASHBOARD" urlPill="app.skillpath.dev/me" litDot="green" shadow="lg">
                <HeroDashboard />
              </AppWindow>

              <div className="mt-4">
                <MiniTerminal command="skillpath start --role frontend" result="✓ roadmap generated" />
              </div>
            </motion.div>
          </div>
        </Container>
      </section>

      {/* Problem Section — Boss Battles (dark game arena) */}
      <section className="relative overflow-hidden bg-cabinet px-4 py-20 text-white">
        {/* Arena floor grid + neon top-light (decorative depth cues, not wallpaper) */}
        <div className="pointer-events-none absolute inset-0 cabinet-grid opacity-25" aria-hidden="true" />
        <div
          className="pointer-events-none absolute inset-x-0 top-0 h-72"
          aria-hidden="true"
          style={{ background: 'radial-gradient(60% 100% at 50% 0%, rgba(255,143,171,0.25), transparent 70%)' }}
        />
        {/* Floating arena doodles */}
        <Landing3DBackground preset="boss" />

        <Container className="relative z-10">
          <Reveal className="mb-14 text-center">
            <StickerBadge variant="boss-fight" label="Boss Battles" size="lg" className="mb-4" />
            <h2 className="mb-4 font-display text-3xl font-black sm:text-5xl">
              Sound <span className="text-pink">familiar?</span>
            </h2>
            <p className="mx-auto max-w-2xl text-on-dark-soft">
              Every developer faces these boss battles. SkillPath helps you defeat them.
            </p>
          </Reveal>

          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {bosses.map((problem, i) => (
              <Reveal key={problem.title} delay={i * 0.08} className="h-full">
                <motion.div
                  className="group h-full"
                  whileHover={prefersReducedMotion ? undefined : { y: -8, rotateX: 6, rotateY: -6 }}
                  whileTap={prefersReducedMotion ? undefined : { scale: 0.98 }}
                  style={{ transformPerspective: 800 }}
                >
                  <div
                    className={cn(
                      'relative flex h-full flex-col p-6 text-black brutal-border brutal-radius shadow-brutal transition-shadow duration-200 group-hover:shadow-brutal-lg',
                      problem.color
                    )}
                  >
                    <span className="absolute right-3 top-3 rounded-md border-2 border-black bg-black px-2 py-0.5 text-[10px] font-black uppercase tracking-wider text-white">
                      Boss
                    </span>
                    <span
                      className="mb-4 inline-flex h-14 w-14 items-center justify-center rounded-xl border-2 border-black bg-white/70 text-4xl"
                      aria-hidden="true"
                    >
                      {problem.emoji}
                    </span>
                    <p className="mb-2 font-display text-lg font-black">{problem.title}</p>
                    <p className="mb-5 flex-1 text-sm font-medium text-black/80">{problem.text}</p>
                    <div className="mt-auto">
                      <div className="mb-1 flex items-center justify-between text-[10px] font-black uppercase tracking-wider">
                        <span>Threat</span>
                        <span className="metric-mono">Lv {i + 1}</span>
                      </div>
                      <div className="h-2.5 overflow-hidden rounded-full border-2 border-black bg-white/50">
                        <div className="h-full bg-black" style={{ width: problem.threat }} />
                      </div>
                    </div>
                  </div>
                </motion.div>
              </Reveal>
            ))}
          </div>
        </Container>
      </section>

      {/* How it Works — Quest Path */}
      <section className="relative overflow-hidden px-4 py-20">
        <Landing3DBackground preset="quest" />
        <Container className="relative z-10">
          <Reveal className="mb-16 text-center">
            <StickerBadge variant="yellow" label="The Quest Path" size="lg" className="mb-4" />
            <h2 className="mb-4 font-display text-3xl font-bold sm:text-4xl">How to Win Your Career Quest</h2>
            <p className="mx-auto max-w-2xl text-secondary">Four worlds to conquer your developer career.</p>
          </Reveal>

          <div className="mx-auto max-w-3xl space-y-6">
            {steps.map((step, i) => (
              <Reveal key={step.number} delay={i * 0.08}>
                <BrutalCardHover
                  color={['yellow', 'blue', 'pink', 'green', 'orange'][i % 5] as CardColor}
                  className="relative flex items-start gap-5 overflow-hidden"
                >
                  {/* Oversized editorial index numeral (decorative) */}
                  <span
                    className="metric-mono pointer-events-none absolute -top-5 right-3 select-none text-7xl font-black text-black/10"
                    aria-hidden="true"
                  >
                    {String(step.number).padStart(2, '0')}
                  </span>

                  <div className="relative shrink-0">
                    <div className="flex h-14 w-14 items-center justify-center bg-black text-white brutal-border brutal-radius">
                      <step.icon className="h-6 w-6" aria-hidden="true" />
                    </div>
                  </div>
                  <div className="relative flex-1">
                    <div className="mb-1 flex flex-wrap items-center gap-2">
                      <span className="hud-label text-[10px] text-secondary">World {step.number}</span>
                      <h3 className="font-display text-heading-sm font-bold">{step.title}</h3>
                      <StickerBadge variant={stepBadgeVariants[i % stepBadgeVariants.length]} label={step.badge} size="sm" />
                    </div>
                    <p className="text-black">{step.description}</p>
                  </div>
                </BrutalCardHover>
              </Reveal>
            ))}
          </div>
        </Container>
      </section>

      {/* Features — Power-Ups */}
      <section className="relative overflow-hidden bg-cream-light px-4 py-20">
        <Landing3DBackground preset="power" />
        <Container className="relative z-10">
          <Reveal className="mb-16 text-center">
            <StickerBadge variant="green" label="Power-Ups" size="lg" className="mb-4" />
            <h2 className="mb-4 font-display text-3xl font-bold sm:text-4xl">Your Developer Power-Ups</h2>
            <p className="mx-auto max-w-2xl text-secondary">Collect these power-ups to level up your career.</p>
          </Reveal>

          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {features.map((feature, i) => (
              <Reveal key={feature.title} delay={i * 0.06} className="h-full">
                <motion.div
                  className="h-full"
                  whileHover={prefersReducedMotion ? undefined : { y: -6, rotateX: 5, rotateY: -5 }}
                  whileTap={prefersReducedMotion ? undefined : { scale: 0.98 }}
                  style={{ transformPerspective: 800 }}
                >
                  <BrutalCard
                    color={feature.color}
                    className="relative h-full overflow-hidden transition-shadow duration-200 hover:shadow-brutal-lg"
                  >
                    <div className="absolute right-2 top-2 opacity-20" aria-hidden="true">
                      <feature.icon className="h-20 w-20" />
                    </div>
                    <span className="hud-label relative z-10 mb-3 block text-[10px] text-black/70">Power-up</span>
                    <feature.icon className="relative z-10 mb-4 h-10 w-10" aria-hidden="true" />
                    <h3 className="relative z-10 mb-2 font-display text-heading-sm font-bold">{feature.title}</h3>
                    <p className="relative z-10 text-sm text-black">{feature.description}</p>
                  </BrutalCard>
                </motion.div>
              </Reveal>
            ))}
          </div>

          {/* See it live — job radar + GitHub tracker windows */}
          <Reveal className="mt-12">
            <div className="grid gap-6 lg:grid-cols-2">
              <JobRadarCard />
              <GitHubTrackerCard />
            </div>
          </Reveal>
        </Container>
      </section>

      {/* Demo Preview — Player Dashboard (one more OS window) */}
      <section className="relative overflow-hidden px-4 py-20">
        <Landing3DBackground preset="demo" />
        <Container className="relative z-10">
          <Reveal className="mb-12 text-center">
            <StickerBadge variant="pink" label="Live Preview" size="lg" className="mb-4" />
            <h2 className="mb-4 font-display text-3xl font-bold sm:text-4xl">See Your Stats in Action</h2>
            <p className="mx-auto max-w-2xl text-secondary">A sneak peek at your player dashboard.</p>
          </Reveal>

          <Reveal className="mx-auto max-w-4xl">
            <AppWindow routeTab="SKILLPATH://DASHBOARD" urlPill="app.skillpath.dev/me" litDot="green" shadow="lg">
              <div className="border-b-3 border-black bg-yellow px-4 pt-4">
                <div className="mb-4 flex items-center justify-between gap-3">
                  <div className="flex items-center gap-4">
                    <div className="flex h-12 w-12 items-center justify-center bg-white brutal-border brutal-radius">
                      <Target className="h-6 w-6" aria-hidden="true" />
                    </div>
                    <div>
                      <p className="font-display font-bold">Your Dashboard</p>
                      <p className="text-sm text-black">Player stats preview</p>
                    </div>
                  </div>
                  <LevelChip level={5} />
                </div>
                {/* Tabs */}
                <div role="tablist" aria-label="Dashboard preview" className="relative top-[3px] flex gap-2">
                  {(['stats', 'quests'] as const).map((tab) => (
                    <button
                      key={tab}
                      role="tab"
                      id={`dashboard-tab-${tab}`}
                      aria-selected={activeTab === tab}
                      aria-controls="dashboard-tabpanel"
                      onClick={() => setActiveTab(tab)}
                      className={cn(
                        'px-4 py-2 text-sm font-bold capitalize brutal-border transition-all focus-brutal-ring',
                        activeTab === tab ? 'bg-white shadow-none' : 'bg-white/60 shadow-brutal-sm hover:bg-white'
                      )}
                      style={{
                        borderBottomWidth: activeTab === tab ? '0px' : '3px',
                        borderBottomLeftRadius: '0px',
                        borderBottomRightRadius: '0px',
                        zIndex: activeTab === tab ? 10 : 1,
                      }}
                    >
                      {tab}
                    </button>
                  ))}
                </div>
              </div>

              <div
                role="tabpanel"
                id="dashboard-tabpanel"
                aria-labelledby={`dashboard-tab-${activeTab}`}
                tabIndex={0}
                className="relative z-0 space-y-6 bg-white p-6 focus-brutal-ring"
              >
                {activeTab === 'stats' && (
                  <motion.div initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} className="grid gap-4 sm:grid-cols-3">
                    <StatTile label="Career Power" value="72" unit="%" icon={Flame} accent="pink" />
                    <StatTile label="Job Match" value="85" unit="%" icon={Target} accent="blue" />
                    <StatTile label="Day Streak" value="5" icon={Zap} accent="green" />
                  </motion.div>
                )}

                {activeTab === 'quests' && (
                  <motion.div initial={{ opacity: 0, x: 10 }} animate={{ opacity: 1, x: 0 }} className="grid gap-4 sm:grid-cols-3">
                    <BrutalCard color="yellow">
                      <div className="mb-2 flex items-center gap-2">
                        <h4 className="font-bold">Current Quest</h4>
                        <StickerBadge variant="in-progress" label="Active" size="sm" />
                      </div>
                      <p className="font-display text-lg font-bold">Frontend Developer</p>
                    </BrutalCard>
                    <BrutalCard color="white">
                      <div className="mb-2 flex items-center gap-2">
                        <h4 className="font-bold">Module</h4>
                        <StickerBadge variant="blue" label="Level 2" size="sm" />
                      </div>
                      <p className="text-lg">React API Patterns</p>
                    </BrutalCard>
                    <BrutalCard color="white">
                      <div className="mb-2 flex items-center gap-2">
                        <h4 className="font-bold">Job Radar</h4>
                        <StickerBadge variant="great-match" label="85%" size="sm" />
                      </div>
                      <p className="text-lg">Junior Frontend Intern</p>
                    </BrutalCard>
                  </motion.div>
                )}

                <div>
                  <h4 className="mb-3 font-bold">Missing Power-Ups</h4>
                  <div className="flex flex-wrap gap-2">
                    {['TypeScript', 'Testing', 'API Integration'].map((skill) => (
                      <StickerBadge key={skill} variant="yellow" label={skill} size="sm" />
                    ))}
                  </div>
                </div>
              </div>
            </AppWindow>
          </Reveal>
        </Container>
      </section>

      {/* CTA — Final Quest */}
      <section className="relative overflow-hidden bg-yellow px-4 py-20">
        <Landing3DBackground preset="cta" />

        <Container className="relative z-10 text-center">
          <Reveal>
            <div
              className="mx-auto mb-6 flex h-20 w-20 items-center justify-center bg-white brutal-border brutal-radius shadow-brutal"
              role="img"
              aria-label="SkillPath cat mascot"
            >
              <span className="text-4xl">🐱</span>
            </div>
            <StickerBadge variant="completed" label="Ready to Start?" size="lg" className="mb-4 inline-flex" />
            <h2 className="mb-4 font-display text-3xl font-black sm:text-4xl">Ready to start your developer quest?</h2>
            <p className="mx-auto mb-8 max-w-2xl text-black">
              Join developers using SkillPath to conquer their careers. It takes 5 minutes to begin.
            </p>
            <Link href="/register">
              <BrutalButton color="black" size="lg" className="shadow-brutal hover:shadow-brutal-lg">
                <Rocket className="h-5 w-5" aria-hidden="true" />
                Start Your Journey
                <ArrowRight className="h-5 w-5" aria-hidden="true" />
              </BrutalButton>
            </Link>
          </Reveal>
        </Container>
      </section>

      {/* Footer */}
      <footer className="bg-black px-4 py-10 text-white">
        <Container>
          <div className="flex flex-col items-center justify-between gap-6 sm:flex-row">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center bg-yellow text-black brutal-border brutal-radius">
                <Sparkles className="h-6 w-6" aria-hidden="true" />
              </div>
              <span className="font-display text-xl font-bold">SkillPath</span>
            </div>

            <p className="text-center text-sm text-gray-300">
              Job data powered by{' '}
              <a
                href="https://remotive.com"
                target="_blank"
                rel="noopener noreferrer"
                className="rounded text-yellow hover:underline focus-brutal-ring-invert"
              >
                Remotive
              </a>
            </p>

            <div className="flex gap-6 text-sm">
              <a
                href="https://github.com"
                target="_blank"
                rel="noopener noreferrer"
                className="rounded text-gray-300 transition-colors hover:text-yellow focus-brutal-ring-invert"
              >
                GitHub
              </a>
              <Link href="/dashboard" className="rounded text-gray-300 transition-colors hover:text-yellow focus-brutal-ring-invert">
                Dashboard
              </Link>
              <Link href="/login" className="rounded text-gray-300 transition-colors hover:text-yellow focus-brutal-ring-invert">
                Login
              </Link>
            </div>
          </div>
        </Container>
      </footer>
    </div>
  )
}
